apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    name: pv-1
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storageclass
  local:
    path: /home/admin/kuber/pvlocal
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kuber2
