kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
spec:
  volumeName: pv-1
  storageClassName: my-storageclass
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi